agents/urls.py
from django.urls import path
from .views import (AgentListView, AgentCreateView,
                    AgentDetailView, AgentUpdateView)

app_name = "agents"
urlpatterns = [
    path("", AgentListView.as_view(), name="agent-list"),
    path('create/', AgentCreateView.as_view(), name='agent_create'),
    path("<int:pk>", AgentDetailView.as_view(), name="agent-detail"),
    path('<int:pk>/update/', AgentUpdateView.as_view(), name='agent-update'),
]

djCrm/urls.py
from django.contrib import admin
from django.urls import path, include
from leads.views import SignupView, HomePage
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", HomePage.as_view(), name="home"),
    path('leads/', include("leads.urls", namespace="leads")),
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path('signup/', SignupView.as_view(), name='signup'),
    path("agents/", include('agents.urls',namespace="agents"))

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

agents/models.py
from django.db import models

# Create your models here.

agents/forms.py
from django import forms
from django.forms import fields
from leads.models import Agent
from django.contrib.auth import get_user_model
User = get_user_model()


class AgentModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

agents/views.py
from django.shortcuts import render
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from leads.models import Agent
from django.shortcuts import reverse
from .forms import AgentModelForm
from .mixins import OrganisorAndLoginRequiredMixin
# Create your views here.


class AgentListView(LoginRequiredMixin, generic.ListView):
    template_name = "agents/agent_list.html"

    def get_queryset(self):
        return Agent.objects.all()


class AgentCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "agents/agent_create.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Agent.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        send_mail(
            subject="You are invited to be an agent",
            message="You were added as an agent on DJCRM. Please come login to start working.",
            from_email="admin@test.com",
            recipient_list=[user.email]
        )
        return super(AgentCreateView, self).form_valid(form)


class AgentDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "agents/agent_detail.html"
    context_object_name = "agent"

    def get_queryset(self):
        return Agent.objects.all()


class AgentUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "agents/agent_update.html"
    form_class = AgentModelForm

    def get_success_url(self):
        return reverse("agents:agent-list")

    def get_queryset(self):
        return Agent.objects.all()

agents/templates/agents/agent_create.html
{% extends "base.html" %} {% block content %}

<div class="max-w-lg mx-auto">
  <div class="py-5 border-b border-gray-200">
    <a class="hover:text-blue-500" href="{% url 'agents:agent-list' %}"
      >Go back to agents</a
    >
  </div>

  <h1 class="text-4xl text-gray-800">Create a new agent</h1>
  <form method="post">
    {% csrf_token %}
    <button
      type="submit"
      class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md"
    >
      Submit
    </button>
  </form>
</div>
{% endblock content %}

agents/templates/agents/agent_detail.html
{% extends 'base.html' %} {% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.username }}
        </h1>
        <div class="flex mb-4">
          <a
            href="{% url 'agents:agent-detail' agent.pk %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Overview</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          >
          <a
            href="{% url 'agents:agent-update' %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Details</a
          >
        </div>
        <p class="leading-relaxed mb-4">
          Fam locavore kickstarter distillery. Mixtape chillwave tumeric
          sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps
          cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine
          tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.
        </p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{ lead.age }}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Pune</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell Phone</span>
          <span class="ml-auto text-gray-900">9999999999</span>
        </div>
        <div class="flex">
          <button
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Button
          </button>
          <button
            class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4"
          >
            <svg
              fill="currentColor"
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              class="w-5 h-5"
              viewBox="0 0 24 24"
            >
              <path
                d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"
              ></path>
            </svg>
          </button>
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_list.html
{% extends "base.html" %} {% block content %}
<section class="text-gray-700 body-font">
  <div class="container px-5 py-24 mx-auto flex flex-wrap">
    <div
      class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200"
    >
      <div>
        <h1 class="text-4xl text-gray-800">Agents</h1>
      </div>
      <div>
        <a
          class="text-gray-500 hover:text-blue-500"
          href="{% url 'agents:agent_create' %}"
          >Create a new agent</a
        >
      </div>
    </div>

    <div class="flex flex-col w-full">
      <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
        <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
          <div
            class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg"
          >
            <table class="min-w-full divide-y divide-gray-200">
              <thead class="bg-gray-50">
                <tr>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Full Name
                  </th>
                  <th
                    scope="col"
                    class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider"
                  >
                    Email
                  </th>
                  <th scope="col" class="relative px-6 py-3">
                    <span class="sr-only">Edit</span>
                  </th>
                </tr>
              </thead>
              <tbody>
                {% for agent in object_list %}
                <tr class="bg-white">
                  <td
                    class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900"
                  >
                    {{ agent.user.first_name }} {{ agent.user.last_name }}
                  </td>
                  <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {{ agent.user.email }}
                  </td>
                  <td
                    class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium"
                  >
                    <a
                      href="{% url 'agents:agent-update' agent.pk %}"
                      class="text-indigo-600 hover:text-indigo-900"
                    >
                      Edit
                    </a>
                  </td>
                </tr>
                {% empty %}

                <p>There are currently no agents</p>

                {% endfor %}
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

agents/templates/agents/agent_update.html
{% extends 'base.html' %} {% block content %}
<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Agent</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">
          {{ agent.user.username }}
        </h1>
        <div class="flex mb-4">
          <a 
            href ="{% url 'agents:agent-detail' agent.pk %}"
            class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Description</a
          >
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1"
            >Reviews</a
          >
          <a
            href="{% url 'agents:agent-update' agent.pk %}"
            class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1"
            >Update Details</a
          >
        </div>
        <form method="POST">
          {% csrf_token %} {{ form.as_p}}
          <button type="submit">submit</button>
        
        <div class="flex">
          <a href="#"
            class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded"
          >
            Delete
          </a>
          
        </div>
      </div>
      <img
        alt="ecommerce"
        class="lg:w-1/2 w-full lg:h-auto h-64 object-cover object-center rounded"
        src="https://dummyimage.com/400x400"
      />
    </div>
  </div>
</section>

{% endblock content %}